gotocy:
  crawl:
    crawlerClass: CyprusRealityCrawler
    crawlStorageFolder: "/home/killer/tmp/crawler"
    numOfCrawlers: 5
    seeds:
      - "http://cyprus-realty.info/"
    cookies:
      -
        domain: ".cyprus-realty.info"
        name: language
        value: en
    filter:
      minPrice: 1000
      maxPrice: 1000000
      propertyStatuses:
        - "SALE"