gotocy:
  crawl:
    crawlerClass: CyprusRealityCrawler
    crawlStorageFolder: "C:\\Users\\ifedorenkov\\Documents\\tmp\\crawler"
    numOfCrawlers: 1
    seeds:
      - "http://cyprus-realty.info/prodazha-nedvizhimosti-na-kipre/villas/15001344/"
    cookies:
      -
        domain: ".cyprus-realty.info"
        name: language
        value: en