gotocy:
  crawl:
    crawlerClass: GiovaniCrawler
    crawlStorageFolder: "/home/killer/tmp/crawler"
    numOfCrawlers: 5
    seeds:
      - "http://giovani.com.cy/properties/"
      - "http://giovani.com.cy/properties/page/2/"
      - "http://giovani.com.cy/properties/page/3/"
      - "http://giovani.com.cy/properties/page/4/"
      - "http://giovani.com.cy/properties/page/5/"
      - "http://giovani.com.cy/properties/page/6/"
      - "http://giovani.com.cy/properties/page/7/"
    filter:
      offerTypes:
        - "SALE"