gotocy:
  crawl:
    crawlerClass: CyprusRealityCrawler
    crawlStorageFolder: "C:\\Users\\ifedorenkov\\Documents\\tmp\\crawler"
    numOfCrawlers: 1
    seeds:
      - "http://cyprus-realty.info/"
    cookies:
      -
        domain: ".cyprus-realty.info"
        name: language
        value: en
    filter:
      maxPrice: 1000000
      propertyStatuses:
        - "SALE"