spring:
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: validate

server:
  tomcat:
    compression: on
    compressableMimeTypes: "application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript"

gotocy:
  webapp:
    email: "support@gotocy.eu"
    phone: "+357 99 166265"
    defaultLatitude: "34.97351552254917"
    defaultLongitude: "33.133228140624965"

---

spring:
  profiles: "heroku-cleardb"
  datasource:
    max-active: 10
    max-idle: 10
    min-idle: 2
    initial-size: 5
    validation-query: "SELECT 1 as pool_test"
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    logAbandoned: true