spring:
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: validate

server:
  compression:
    enabled: "true"
    mimeTypes: "application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript"
  session:
    tracking-modes: "COOKIE"
    cookie:
      http-only: true

multipart:
  enabled: "true"
  maxFileSize: "10Mb"
  maxRequestSize: "-1"


gotocy:
  webapp:
    email: "support@gotocy.com"
    phone: "+357 96 698624"
    defaultLatitude: "34.97351552254917"
    defaultLongitude: "33.133228140624965"
    defaultContact:
      name: "Denis"
      email: "denis@gotocy.com"
      phone: "+357 96 698624"
      spokenLanguages: "Eng, Rus"
    defaultRepresentativeImage:
      key: "static/img/no-image.jpg"